const $=s=>document.querySelector(s);
const LABELS=['Aのそばで待つ','終了前に戻る','Bを終えて戻る'];
const COLORS={auto:'#bfe0f0',response:'#2261a7',other:'#0a8073',travel:'#7556aa',idle:'#d8e1eb',waiting:'#bc2949'};
const WORDS={auto:'自動運転',response:'Aの終了対応',other:'Bの手作業',travel:'移動',idle:'手待ち',waiting:'戻り待ち'};
const fmt=n=>Number(n.toFixed(1));
const clock=n=>{const m=Math.floor(n);return `${9+Math.floor(m/60)}:${String(m%60).padStart(2,'0')}`;};
const delta=n=>n===0?'待つ案と同じ':`${fmt(Math.abs(n))}分${n<0?'早い':'遅い'}`;
let selected='reset',time=15,horizon=70,result,input,playing=false,lastFrame=0;
function read(){const x={...EXAMPLE,outMin:Number($('#travel').value),backMin:Number($('#travel').value),otherMin:Number($('#work').value),interruptible:$('#can-pause').checked,urgent:$('#priority').checked};for(const e of document.querySelectorAll('[data-key]'))x[e.dataset.key]=e.type==='checkbox'?e.checked:(e.value===''?null:Number(e.value));return x;}
function progress(row,lane,t){return row.segments.filter(s=>s.lane===lane&&s.kind!=='waiting').reduce((n,s)=>n+Math.max(0,Math.min(t,s.end)-s.start),0);}
function worker(row,t){let loc=0;for(const s of row.segments.filter(s=>s.lane==='worker').sort((a,b)=>a.start-b.start)){
 if(t<s.start) return {loc,kind:'idle'};
 if(s.kind==='travel'){const target=1-loc;if(t<s.end)return {loc:loc+(target-loc)*(t-s.start)/(s.end-s.start),kind:'travel',direction:target>loc?'Bへ移動中':'Aへ戻る途中'};loc=target;}
 else{loc=s.kind==='other'?1:s.kind==='response'?0:loc;if(t<s.end)return {loc,kind:s.kind};}
 }return {loc,kind:'done'};}
function human(x,y){return `<g transform="translate(${x} ${y})"><circle cy="-13" r="13" fill="white" opacity=".9"/><circle cy="-18" r="7" fill="#17283f"/><path d="M-9 -7 Q0 -13 9 -7 L8 6 L-8 6Z" fill="#17283f"/><path d="M-5 6 L-8 17 M5 6 L8 17" stroke="#17283f" stroke-width="4" stroke-linecap="round"/></g>`;}
function station(x,type,pc,status,alert){const color=type==='A'?'#2261a7':'#0a8073',circ=2*Math.PI*35;return `<g transform="translate(${x} 64)"><circle r="35" fill="#f8faff" stroke="#e4eaf2" stroke-width="5"/><circle r="35" fill="none" stroke="${alert?'#bc2949':color}" stroke-width="5" stroke-dasharray="${circ*pc} ${circ}" transform="rotate(-90)"/>${type==='A'?'<path d="M-17 16 V-19 H17 V16 M-21 16 H21 M-11 -12 H10 V2 H-11Z" fill="none" stroke="#2261a7" stroke-width="3" stroke-linejoin="round"/><circle cx="11" cy="10" r="2" fill="#2261a7"/><path d="M-10 10 H3" stroke="#2261a7" stroke-width="3"/>':'<path d="M-23 5 H23 M-18 5 V20 M18 5 V20" stroke="#0a8073" stroke-width="4"/><path d="M-10 3 V-13 H9 V3Z M-3 -13 V-20 H15 V-8" fill="none" stroke="#0a8073" stroke-width="3"/>'}<text y="-47" text-anchor="middle" font-size="13" font-weight="750" fill="${color}">${type==='A'?'A 自動測定機':'B 検査台'}</text><text y="56" text-anchor="middle" font-size="13" font-weight="700" fill="${alert?'#bc2949':'#17283f'}">${status}</text><text y="74" text-anchor="middle" font-size="11" fill="#596b82">${Math.floor(pc*100)}% 完了</text><text y="92" text-anchor="middle" font-size="10" fill="#596b82">${type==='A'?`自動 ${fmt(input.autoMin)}分 ・ ${clock(input.autoMin)}終了`:`手作業 ${fmt(input.otherMin)}分`}</text></g>`;}
function scene(r,i){const w=worker(r,time),left=100-input.outMin*2,right=240+input.outMin*2,x=left+(right-left)*w.loc;const waiting=time>=input.autoMin&&time<r.aEnd-input.responseMin;
 const aStatus=time>=r.aEnd?'完了 ✓':waiting?'人の戻り待ち':time<input.autoMin?`自動 残り${fmt(input.autoMin-time)}分`:'終了対応中';
 const bDone=progress(r,'B',time),bStatus=time>=r.bEnd?'完了 ✓':w.kind==='other'?`検査 残り${fmt(input.otherMin-bDone)}分`:bDone>0?'中断・再開待ち':'未着手';
 return `<svg class="map" viewBox="0 0 340 258" role="img" aria-label="${clock(time)} ${aStatus}、B ${bStatus}、作業者は${w.direction||WORDS[w.kind]||'作業完了'}"><defs><marker id="arr${i}" markerWidth="7" markerHeight="7" refX="6" refY="3" orient="auto-start-reverse"><path d="M0 0 L6 3 L0 6" fill="none" stroke="#a899bf"/></marker></defs>${station(left,'A',Math.min(1,progress(r,'A',time)/(input.autoMin+input.responseMin)),aStatus,waiting)}${station(right,'B',Math.min(1,bDone/input.otherMin),bStatus,false)}<path d="M${left} 202 H${right}" stroke="#ddd6e9" stroke-width="8" stroke-linecap="round"/><path d="M${left+14} 224 H${right-14}" stroke="#a899bf" stroke-width="1.5" marker-start="url(#arr${i})" marker-end="url(#arr${i})"/><text x="170" y="246" text-anchor="middle" fill="#7556aa" font-size="12">片道 ${fmt(input.outMin)}分 ／ 往復 ${fmt(input.outMin+input.backMin)}分</text>${human(x,196)}${waiting?`<circle cx="${left+31}" cy="37" r="10" fill="#bc2949"/><text x="${left+31}" y="42" text-anchor="middle" font-size="14" fill="white" font-weight="800">!</text>`:''}</svg>`;
}
function gantt(r,i){const L=65,W=355,X=t=>L+W*t/horizon,rows=[['worker','人',38],['A','A',78],['B','B',118]];
 return `<svg class="chart" data-chart="${i}" viewBox="0 0 440 163" role="img" aria-label="${LABELS[i]}の人・ロット別時間軸。クリックで時刻を移動"><defs><pattern id="wait${i}" patternUnits="userSpaceOnUse" width="6" height="6" patternTransform="rotate(45)"><rect width="6" height="6" fill="#f9dce4"/><rect width="2" height="6" fill="#bc2949"/></pattern></defs>${Array.from({length:Math.floor(horizon/10)+1},(_,n)=>`<line x1="${X(n*10)}" x2="${X(n*10)}" y1="20" y2="139" stroke="#e6ecf3"/><text x="${X(n*10)}" y="155" text-anchor="middle" font-size="10" fill="#65778d">${clock(n*10)}</text>`).join('')}${rows.map(([lane,name,y])=>`<text x="20" y="${y+5}" fill="#53667c" font-size="12" font-weight="700">${name}</text><rect x="${L}" y="${y-10}" width="${W}" height="22" rx="4" fill="#f2f5f9"/>${r.segments.filter(s=>s.lane===lane).map(s=>`<g><title>${WORDS[s.kind]} ${clock(s.start)}〜${clock(s.end)}</title><rect x="${X(s.start)}" y="${y-10}" width="${W*(s.end-s.start)/horizon}" height="22" rx="3" fill="${s.kind==='waiting'?`url(#wait${i})`:COLORS[s.kind]}"/>${s.end-s.start>=9?`<text x="${X((s.start+s.end)/2)}" y="${y+4}" text-anchor="middle" fill="${['other','response','travel'].includes(s.kind)?'white':'#29405a'}" font-size="10">${WORDS[s.kind]}</text>`:''}</g>`).join('')}${lane!=='worker'?deadline(lane,y,r,X,i):''}`).join('')}<line x1="${X(time)}" x2="${X(time)}" y1="16" y2="138" stroke="#17283f" stroke-width="1.7"/><path d="M${X(time)-4} 13 L${X(time)+4} 13 L${X(time)} 19Z" fill="#17283f"/></svg>`;
}
function deadline(lane,y,r,X,i){const due=lane==='A'?input.dueA:input.dueB,end=lane==='A'?r.aEnd:r.bEnd;if(due===null)return '';return `<line x1="${X(due)}" x2="${X(due)}" y1="${y-18}" y2="${y+16}" stroke="#bc2949" stroke-dasharray="3 2"/><path d="M${X(due)} ${y-19} l8 0 l-3 4 l-5 0Z" fill="#bc2949"/>${end>due?`<rect x="${X(due)}" y="${y+11}" width="${X(end)-X(due)}" height="4" fill="#bc2949"/>`:''}`;}
function blocked(r,i){return `<article class="plan"><div class="plan-head"><div><span class="ordinal">PLAN 0${i+1}</span><h2>${LABELS[i]}</h2></div><span class="verdict neutral">選べない</span></div><div class="blocked-panel"><svg viewBox="0 0 100 100" aria-hidden="true"><circle cx="50" cy="50" r="37" fill="#f0f3f8" stroke="#b7c4d6" stroke-width="3"/><path d="M25 75L75 25" stroke="#b7c4d6" stroke-width="5"/>${human(50,52)}</svg><b>この条件では移動しません</b><p>${r.reason}</p></div></article>`;}
function draw(){if(!result||result.status!=='ok')return;$('#clock').textContent=clock(time);$('#time').value=time;
 $('#plans').innerHTML=result.rows.map((r,i)=>{if(r.status!=='ok')return blocked(r,i);const w=worker(r,time),waiting=time>=input.autoMin&&time<r.aEnd-input.responseMin;
 const now=waiting?`Aが停止。作業者の帰り待ち ${fmt(time-input.autoMin)}分`:w.kind==='done'?'2ロットとも完了':w.direction||({idle:'Aのそばで待機',other:'Bの検査を進めています',response:'Aの終了対応をしています'})[w.kind];
 const verdict=r.deadlineUnknown?'締切不明':r.lateA||r.lateB?'締切を超える':'締切内に完了';
 return `<article class="plan"><div class="plan-head"><div><span class="ordinal">PLAN 0${i+1}</span><h2>${LABELS[i]}</h2></div><span class="verdict ${r.deadlineUnknown?'neutral':r.lateA||r.lateB?'bad':''}">${verdict}</span></div>${scene(r,i)}<div class="now-strip ${waiting?'alert':''}" aria-live="off"><span class="dot"></span>${now}</div><div class="result"><div><small>A 完了見込み</small><b>${clock(r.aEnd)}</b><em class="${r.lateA?'bad':''}">${r.lateA?`締切 +${fmt(r.lateA)}分`:r.delta&&i?delta(r.delta.a):r.lateA===null?'締切不明':'基準'}</em></div><div><small>B 完了見込み</small><b>${clock(r.bEnd)}</b><em class="${r.lateB?'bad':''}">${r.lateB?`締切 +${fmt(r.lateB)}分`:r.delta&&i?delta(r.delta.b):r.lateB===null?'締切不明':'基準'}</em></div></div>${gantt(r,i)}<div class="mini-foot"><span>人の手待ち <b>${fmt(r.idleMin)}分</b></span><span>移動 <b>${fmt(r.travelMin)}分</b></span><span>Aの戻り待ち <b>${fmt(r.machineWaitMin)}分</b></span></div></article>`;}).join('');
 for(const svg of document.querySelectorAll('[data-chart]'))svg.onclick=e=>{const b=svg.getBoundingClientRect();time=Math.max(0,Math.min(horizon,((e.clientX-b.left)/b.width*440-65)/355*horizon));stop();draw();};
}
function recalc(){stop();input=read();result=compare(input);$('#error').textContent=result.status==='ok'?'':result.errors.join(' / ');if(result.status!=='ok'){$('#plans').innerHTML='';$('#fit').textContent='条件を確認してください';return;}horizon=Math.ceil(Math.max(60,...result.rows.filter(r=>r.status==='ok').map(r=>r.pairEnd),input.dueA||0,input.dueB||0)/10)*10;$('#time').max=horizon;$('#end-clock').textContent=clock(horizon);time=Math.min(time,horizon);$('#travel-value').textContent=fmt(input.outMin)+'分';$('#work-value').textContent=fmt(input.otherMin)+'分';for(const id of ['reset','delay','urgent'])$('#'+id).setAttribute('aria-pressed',String(selected===id));
 const total=input.outMin+input.otherMin+input.backMin+input.marginMin,den=Math.max(total,input.autoMin),part=(n,c)=>`<span style="width:${n/den*100}%;background:${c}"></span>`;
 $('#fit').innerHTML=`<div class="fitkey"><span>自動運転</span><b>${fmt(input.autoMin)}分</b></div><div class="fit">${part(input.autoMin,'#8cc5dd')}</div><div class="fitkey"><span>行き ＋ B作業 ＋ 帰り ＋ 余裕</span><b>${fmt(total)}分</b></div><div class="fit">${part(input.outMin,COLORS.travel)}${part(input.otherMin,COLORS.other)}${part(input.backMin,COLORS.travel)}${part(input.marginMin,'#d8e1eb')}</div><div class="reason" style="color:${total>input.autoMin?'#bc2949':'#0a8073'}">${total>input.autoMin?`全量を終えて戻るには ${fmt(total-input.autoMin)}分 足りない`:`往復しても、戻り余裕とは別に ${fmt(input.autoMin-total)}分 残る`}</div>`;draw();}
function stop(){playing=false;$('#play').textContent='▶ 再生';lastFrame=0;}
function frame(ts){if(!playing)return;if(lastFrame)time=Math.min(horizon,time+(ts-lastFrame)/1000*2);lastFrame=ts;draw();if(time>=horizon)stop();else requestAnimationFrame(frame);}
$('#play').onclick=()=>{if(playing){stop();return;}if(!result||result.status!=='ok')return;if(time>=horizon)time=0;playing=true;$('#play').textContent='Ⅱ 一時停止';requestAnimationFrame(frame);};
$('#time').oninput=()=>{stop();time=Number($('#time').value);draw();};
$('#start').onclick=()=>{stop();time=0;draw();};$('#auto-end').onclick=()=>{stop();time=Math.min(horizon,input.autoMin);draw();};
function preset(id){selected=id;$('#travel').value=3;$('#work').value=id==='reset'?20:30;$('#can-pause').checked=false;$('#priority').checked=id==='urgent';for(const e of document.querySelectorAll('[data-key]'))e.type==='checkbox'?e.checked=EXAMPLE[e.dataset.key]:e.value=EXAMPLE[e.dataset.key];time=id==='reset'?15:30;recalc();}
for(const id of ['reset','delay','urgent'])$('#'+id).onclick=()=>preset(id);
for(const e of document.querySelectorAll('[data-key],#travel,#work,#can-pause,#priority'))e.addEventListener('input',()=>{selected='custom';recalc();});
$('#save').onclick=()=>{if(!result||result.status!=='ok')return;const blob=new Blob([JSON.stringify({schemaVersion:1,kind:'parallel-lab-experiment',productionEligible:false,result},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='parallel-experiment.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
preset('reset');
